---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/bragai22/bragaservices.com/
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp public/index_hostgator.php $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R var $DEPLOYPATH
    - /bin/mv -f $DEPLOYPATH/index_hostgator.php $DEPLOYPATH/index.php

